name: edumate
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3 

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15
  intl: ^0.18.0
  jwt_decode: ^0.3.1
  http: ^1.2.2
  provider: ^6.1.2
  permission_handler: ^11.3.1
  flutter_svg: ^2.0.10
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
